# Generated by Django 5.1 on 2025-01-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250107_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requires_prescription',
            field=models.BooleanField(default=False),
        ),
    ]
